FROM alpine:3.11

MAINTAINER yangkai yangkainn@gmail.com

RUN set -ex \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add --no-cache python python-dev py-pip \
    && apk add --no-cache --virtual .build-deps \
           gcc g++ linux-headers openssl-dev \
    && pip install influxdb redis \
    && apk del .build-deps \
    && apk add -U tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone \
    && rm -rf /tmp/* /var/cache/* /var/log/*

ADD . /opt

WORKDIR /opt

CMD ["python2.7","./test.py"]
