FROM centos:6.10 as builder

MAINTAINER yangkai yangkainn@gmail.com

RUN set -ex \
    && rm -f /etc/yum.repos.d/* \
    && curl http://mirrors.aliyun.com/repo/Centos-6.repo > /etc/yum.repos.d/CentOS-Base.repo \
    && curl http://mirrors.aliyun.com/repo/epel-6.repo > /etc/yum.repos.d/epel.repo \
    && yum groupinstall -y 'development tools' \
    && yum install -y curl wget \
           lua-socket zlib-dev openssl-devel sqlite-devel bzip2-devel xz-libs \
    && cd /usr/local/src \
    && wget https://www.python.org/ftp/python/2.7.8/Python-2.7.8.tar.xz \
    && tar xvfJ Python-2.7.8.tar.xz \
    && cd Python-2.7.8 \
    && ./configure --prefix=/usr/local/python2.7 \
    && make \
    && make altinstall \
    && ln -sf /usr/local/python2.7/bin/* /usr/local/bin/ \
    && cd /usr/local/src \
    && wget https://bootstrap.pypa.io/ez_setup.py \
    && python2.7 ez_setup.py install \
    && wget https://pypi.python.org/packages/source/p/pip/pip-9.0.1.tar.gz --no-check-certificate \
    && tar zxvf pip-9.0.1.tar.gz \
    && cd pip-9.0.1 \
    && python2.7 setup.py install

RUN set -ex \
    && ln -sf /usr/local/python2.7/bin/* /usr/local/bin/ \
    && pip install jinja2 influxdb

FROM centos:6.10
# 从builder中复制编译好的python2.7
COPY --from=builder /usr/local/python2.7 /usr/local

RUN ln -sf /usr/local/python2.7/bin/* /usr/local/bin/

RUN set -ex \
    && rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm \
    && yum install -y net-tools \
    && yum clean all \
    && rm -rf /tmp/* /var/cache/* /var/log/*

ADD . /opt/

RUN set -ex \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && ln -sf /opt/nettest /usr/local/ \
    && ln -sf /opt/zeromq/ld.so.conf.d/zeromq.conf /etc/ld.so.conf.d/ \
    && ldconfig

WORKDIR /opt

CMD ["python2.7","./entrypoint.py"]
